title: Nichole Breeland | Social Cognition Researcher
logo: NicholeBreeland.github.io/headshot.jpeg
description: Minimal is a theme for GitHub Pages.
google_analytics: UA-179501623-1
theme: jekyll-theme-minimal
